apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: aiweo7b0n-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-65dfe48712.189w.p3.openshiftapps.com/rhtap/rhtap-qe-java-springboot:6b7b6c7f7956f11423de7a2b4aa7836869f61d43@sha256:e9442fe09000a979cb8f79363ab6a1482e16c92d082557e18963f2c12658f732
          name: container-image
